### ISSUE TITLE
Roadmap: @waline/vercel@v2 and @waline/client@v3

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#1669]
### 功能概述 | Describe the feature

The issue record breaking changes to be made in next major version.

We may need a migration helper to convert database into the new format.

## Migration helper rebuild

- [ ] Improve migration helper.

## Ensure no markdown is in comment

- [ ] Comments before 2021 and comments from valine may still have markdown stored.

## Change reply @  into client

https://github.com/walinejs/waline/issues/1649

This requires:

- [ ] Migration helper to remove exisiting prefix in comment
- [ ] Client support
- [ ] Server changes

## Convert `user_id` to `userId` for comment data structure

- [ ] To have a constant key named rule with camelCase.

## New API replacing old ones

- [ ] `/comment?type=count&url=URL` will return inconstant data type, and new API should return `number[]`, so should `/article?type=TYPES`

## Remove legacy package

- [ ] V3 shall drop compatability with Valine.

**Comment by lizheming** [comment]
> Convert user_id to userId for comment data structure, to have a constant key named rule with camelCase.

What's the purpose of this? CamelCase is not friendly for SQL like storage service, I have headache to some camelCase fields already.

**Comment by Mister-Hope** [comment]
To unify data structrure, all other keys are camelcase like `insertedAt` `objectId` etc.

If you do think it's not ok for changing this key, I still suggest making a convertion to camelCase for this key before returning data to client.

**Comment by Mister-Hope** [comment]
> To unify data structrure, all other keys are camelcase like `insertedAt` `objectId` etc (or in another word, this is the only kebab_case key in client package and whole api.
> 
> If you do think it's not ok for changing this key, I still suggest making a convertion to camelCase in server for this key before returning data to client. We have 3rd party clients, and it's better for us to provide a unified data structure, and more easy-understanding apis. We could remain old apis.

Any ideas with this one? Technically speaking, I think it's better for us to provide new apis while remaining the old one. @lizheming 

Also I would like to work on v3 for the above changes.

**Comment by lolifamily** [comment]
![image](https://github.com/walinejs/waline/assets/47876607/ebd00107-e1bd-410b-963f-aa289d938cb2)
the server's demo page '/' is still using the old API!
